### ISSUE TITLE
我克隆项目运行安卓项目的时候遇到一个问题

### ISSUE THREAD

**Issue by quietautumn** [lizhuoyuan/React_Navigation#1]
![def86c7e-39e6-4646-b52a-690154f42f34](https://user-images.githubusercontent.com/16301518/40223800-cd136ffa-5ab6-11e8-9d56-567eb23cc2c5.png)

**Comment by lizhuoyuan** [comment]
可能你需要重新构建一下Android项目

**Comment by quietautumn** [comment]
@lizhuoyuan 就是因为对安卓不懂，所以想找一个能直接运行的例子学习一下，我自己按照你的博客教程调用原生安卓也是会报错，提示找不到类。但是相关代码都放进去了的

**Comment by lizhuoyuan** [comment]
稍等我看一眼安卓项目

**Comment by lizhuoyuan** [comment]
更新一下代码 应该是有个资源文件没有上传的愿意 ， 还不行的话 可以反馈给我

**Comment by quietautumn** [comment]
更新之后刚刚开始编译就开始报错了
![984be729-b85d-4537-96f2-4e56dd471f04](https://user-images.githubusercontent.com/16301518/40227397-f87bb044-5ac0-11e8-92a8-a6cdb8505070.png)

**Comment by lizhuoyuan** [comment]
https://github.com/lizhuoyuan/React_Navigation/network 去着里 找个往前一点的分支。。
我不知道我同事给我上传了什么代码。。

**Comment by quietautumn** [comment]
谢谢lz，之前那个问题的原因我应该已经找到了，可能是因为package包名一直是用的你们的包名，麻烦了哈。
